### ISSUE TITLE
Update repo structure

### ISSUE THREAD

**Issue by jgrandja** [jzheaux/spring-security-oauth2-resource-server#1]
We want to ensure that the code in this repo is easily _lifted_ and merged into Spring Security via a PR when it's ready.

So to help with this transition, I propose the following:

**Module Name**
The name of this repo `spring-security-oauth2-resource-server` will also become the Spring Security module name. Alternatively, `spring-security-oauth2-resource-provider` to avoid possible naming collision with reactive implementation?

**Folder Structure**
root -> oauth2 -> oauth2-resource-server (or oauth2-resource-provider)
root -> samples -> boot -> oauth2

**Base Package**
`org.springframework.security.oauth2.server.resource`
`org.springframework.security.oauth2.provider.resource`

What are your thoughts @rwinch, @jzheaux, @vpavic?

**Comment by vpavic** [comment]
The spring-projects/spring-security#5122 which adds initial Resource Server bits is inline with this.

I personally prefer to use the domain language i.e. keep the naming inline with the specs. Which means  server get my vote over provider.

**Comment by jgrandja** [comment]
@vpavic I totally agree in using the domain language defined in spec for our naming as well. We just need to ensure it doesn't collide when we start implementing the reactive end of things as `server` is used as a sub-package.

**Comment by jzheaux** [comment]
It's not sexy, but we could do `org.springframework.security.oauth2.resourceserver` (and then `org.springframework.security.oauth2.authorizationserver` for the AS), which would free up the `server` package part for the reactive naming convention.

**Comment by vpavic** [comment]
> It's not sexy, but we could do `org.springframework.security.oauth2.resourceserver` (and then `org.springframework.security.oauth2.authorizationserver` for the AS), which would free up the `server`  package part for the reactive naming convention.

I had the same idea initially and am starting to lean back towards this option.

Although it might seem clumsy at first, IMO keeping `client`, `resourceserver` and `authorizationserver` at same level is a good thing. We're also sticking with the domain naming and aren't introducing something like resource provider, while keeping `server` package free.

**Comment by jgrandja** [comment]
Yeah I had the same idea initially as well but it never really felt right. It just seems too long of a sub-package name. I do agree that keeping it at the same level is a good thing. Either way, all very good points so we'll keep mulling over it for now.

**Comment by jzheaux** [comment]
While `authorizationserver` is a bit lengthy, I think we should also beware of sidestepping the length by splitting up a subpackage by its words when that extra hierarchy level is unlikely to be leveraged. In the end, `provider.resource` is actually longer than `resourceserver`, and I would guess that classes would always fall under `provider.resource` and not under just `provider`.

That said, we could also do `org.springframework.security.oauth2.rs` (and then `org.springframework.security.oauth2.as`). We lose a little bit of clarity, but not much, given the context that the `oauth2` parent sub-package gives. If these abbreviations are prevalent online, then we might be able to get away with it. We do so with `crypto`, `cas`, `ldap`, `csrf`, and others.
