### ISSUE TITLE
OAuth2TokenVerifier.verify(Map) -> OAuth2TokenVerifier.verify(T extends AbstractOAuth2Token)

### ISSUE THREAD

**Issue by rwinch** [jzheaux/spring-security-oauth2-resource-server#19]
Consider changing the verifier signature to accept a generic type that extends `AbstractOAuth2Token` to have a richer object model. This ensures users inject an `OAuth2TokenVerifier` that works with the class that needs it. For example:

```java
public interface OAuth2TokenVerifier<T extends AbstractOAuth2Token> {

	void verify(T token) throws OAuth2AuthenticationException;

}
````

This would allow us to fix other places in the code to be type safe and still rely on interfaces. For example, `JwtAccessTokenAuthenticationProvider` currently relies on `JwtAccessTokenVerifier` which is a class. If we make the changes above, we could inject `OAuth2TokenVerifier<Jwt>` instead.

Using a subclass of `AbstractOAuth2Token` instead of `Map` also provides a richer domain model for `OAuth2TokenVerifier`.

**Comment by jgrandja** [comment]
@rwinch You beat me to this issue! I had a note to add this. This totally makes sense and I agree on all points.

**Comment by jzheaux** [comment]
One concern with this (now that I've begun implementing it), is that typing the parameter will make it a little tricker to share a verifier across multiple formats. 

I don't think we lose much with this, but mentioning it here in case anyone sees a gotcha.

**Comment by jzheaux** [comment]
Let's say that we have a custom verifier that checks a particular claim, say the "iss" claim.

```java
public void verify(Map<String, Object> attributes) {
    Assert.assertNotNull(attributes.get("iss"), "iss cannot be null");
}
```

The above verifier isn't directly tied to JWT, but instead can verify any token 
to have the "iss" claim. For example, this class could be reused for an opaque token flow after it is exchanged for a set of claims:

```java
oauth2().resourceServer()
  .addVerifier(issuerVerifier())
  .jwt()
  .opaque();
```

With the new contract, we'd do something maybe like this:

```java
public void verify(AbstractOAuth2Token token) {
    String iss;
    if ( token instanceof Jwt ) {
        iss = ((Jwt) token).getIssuer();
    } else if ( token instanceof MyOtherTokenType ) {
        iss = (String) ((MyOtherTokenType) token).getClaimAsString("iss");
    } else {
        // ... exception
    }

    // ... assert
}
```
if we wanted to try and reuse. Though personally, I would prefer doing:

```java
public void verify(Jwt token) {
    Assert.assertNotNull(token.getIssuer());
}

// ... and

public void verify(MyOtherTokenType token) {
    Assert.assertNotNull(token.getClaimAsString("iss"));
}
```
and tying them directly to the token type, which would mean possibly doubling up on the number of verifiers:

```java
oauth2().resourceServer()
  .jwt()
    .addVerifier(jwtBasedIssuerVerifier())
  .opaque()
    .addVerifier(myOtherTokenTypeIssuerVerifier());
```

To be clear, I think this is a minor trade off. The stronger typing that we get, and the encapsulation benefit as well, are more important.

**Comment by jgrandja** [comment]
> Taking a quick look at the current implementations of `AbstractOAuth2Token`, I'm not certain that adding a getAttributes method there is on the table

`AbstractOAuth2Token` defines the **minimal** set of attributes whereas `OAuth2AccessToken` defines the additional attributes defined by [RFC 6749](https://tools.ietf.org/html/rfc6749#section-5.1). So IMO it wouldn't make sense to define `getAttributes()` here since we already provide accessors to each of the attributes.

> ...though the original contract for verify (taking a Map) kind of implies that we only anticipate(d) verifying tokens that have attributes.

`Jwt` and `IntrospectedAccessToken` (future) do have additional attributes so these would be the types evaluated in `OAuth2TokenVerifier`.
