### ISSUE TITLE
Resource Server Configuration should include SpEL OAuth2 expressions bean

### ISSUE THREAD

**Issue by jzheaux** [jzheaux/spring-security-oauth2-resource-server#31]
We don't want users to have to do:

```java
@Bean
public OAuth2Expressions oauth2() {
    return new DefaultOAuth2Expressions();
}
```

**Comment by jgrandja** [comment]
The `oauth2` `@Bean` should be defined in the `ResourceServerSecurityConfigurer` #13

**Comment by jzheaux** [comment]
Resolved with https://github.com/jzheaux/spring-security-oauth2-resource-server/commit/3ee647831bf86ba5234a695067fb1ad8e7c0dcfa
