### ISSUE TITLE
Authorities Extraction

### ISSUE THREAD

**Issue by jzheaux** [jzheaux/spring-security-oauth2-resource-server#37]
There are myriad ways to represent authorities in OAuth2 that go beyond `scope`. We need a hook so code can transform any custom representation of roles in access tokens into Spring Security roles:

```java
Collection<? extend GrantedAuthority> extractAuthorities(AbstractOAuth2Token token)
```

**Comment by rwinch** [comment]
I'd prefer to make this a bit more generic. Accepting an Authentication and returning an Authentication would be ideal. This allows for more powerful transformations.

**Comment by jzheaux** [comment]
Ah, I just reread your comment, and I missed that you prefer a contract that returns an Authentication as well. Will take a look.
