### ISSUE TITLE
Refactor `OAuth2ResourceAuthenticationFilter`

### ISSUE THREAD

**Issue by vpavic** [jzheaux/spring-security-oauth2-resource-server#4]
The `OAuth2ResourceAuthenticationFilter` should go into `org.springframework.security.oauth2.resource.web` package rather than `org.springframework.security.oauth2.resource.authentication`.

**Comment by vpavic** [comment]
Perhaps it should also be renamed to `BearerTokenAuthenticationProcessingFilter`.

**Comment by jzheaux** [comment]
Sounds good, will move. Regarding the name, I think that `BearerTokenAuthenticationFilter` might suit better. It no longer extends `AbstractAuthenticationProcessingFilter` as it did originally. Do you have any concerns with dropping `Processing` from the name?

**Comment by vpavic** [comment]
`BearerTokenAuthenticationFilter` does look better.
