### ISSUE TITLE
Race condition in BearerTokenAuthenticationFilter

### ISSUE THREAD

**Issue by rwinch** [jzheaux/spring-security-oauth2-resource-server#48]
Fix race condition in `BearerTokenAuthenticationFilter`

In general doing the following is a [race condition](https://docs.spring.io/spring-security/site/docs/current/reference/htmlsingle/#tech-intro-sec-context-persistence):

```java
SecurityContextHolder.getContext().setAuthentication(authenticationResult);
```

Instead invoke:

```java
SecurityContext context = SecurityContextHolder.createEmptyContext();
context.setAuthentication(authenticationResult);
SecurityContextHolder.setContext(context);
```

**Comment by jzheaux** [comment]
This might be a good sonar rule.
