### ISSUE TITLE
Convert to Gradle build

### ISSUE THREAD

**Issue by vpavic** [jzheaux/spring-security-oauth2-resource-server#5]
IMO we should convert this repo to be built by Gradle and apply conventions used in Spring Security build (Checkstyle, etc.), in order to help minimize the effort when the time comes to merge this to main repo.

@jzheaux If you're agree with the proposal above, I can take on this (feel free to assign).

**Comment by jzheaux** [comment]
Agreed.

Thanks for volunteering, I appreciate it!

**Comment by vpavic** [comment]
Thanks @jzheaux but I've already got this in local branch and will push shortly.

**Comment by jzheaux** [comment]
Splendid. Thanks.

**Comment by vpavic** [comment]
This has been resolved by:

- converting to Gradle build (uses convention plugin)
- adding code style config files, enabling EditorConfig support and Checkstyle
- fixing code to adhere to Checkstyle checks
