### ISSUE TITLE
OAuth2TokenVerifier Exception vs Return type

### ISSUE THREAD

**Issue by rwinch** [jzheaux/spring-security-oauth2-resource-server#53]
I wonder if a return type is better for OAuth2TokenVerifier vs throwing an exception. In places we need an exception we would use the result to create the Exception. Remember anytime we create an Exception it is slow to populate the stacktrace.

**Comment by jzheaux** [comment]
Is this a duplicate of #24? Want to make sure I'm capturing the difference if not.

**Comment by rwinch** [comment]
You are right. I had thought I created an issue around that but for some reason couldn't find it.

**Comment by rwinch** [comment]
Closing as duplicate
