### ISSUE TITLE
Problem with invoking NimbusOpaqueTokenIntrospector with deprecated ClientCredentialsResourceDetails and OAuth2RestTemplate 

### ISSUE THREAD

**Issue by sandeepvedavyas** [jzheaux/spring-security-oauth2-resource-server#60]
I am trying to invoke introspection uri with rest options to get auth token but  ClientCredentialsResourceDetails and OAuth2RestTemplate are deprecated, any best way to implement it with Webclient on NimbusOpaqueTokenIntrospector introspector? 

  override fun configure(http: HttpSecurity) {
		http
				.authorizeRequests { authz ->
					authz
							.antMatchers("/hello")
							.authenticated()
				}
				.oauth2ResourceServer { oauth2: OAuth2ResourceServerConfigurer<HttpSecurity?> ->
					oauth2
							.opaqueToken { token ->
								val resourceDetails = ClientCredentialsResourceDetails()
								resourceDetails.accessTokenUri = "https://**.com/oauth2/token"
								resourceDetails.clientId = clientId
								resourceDetails.clientSecret = clientSecret
								resourceDetails.scope = listOf("hydra/*")

								val restTemplate = OAuth2RestTemplate(resourceDetails)

								token.introspector(NimbusOpaqueTokenIntrospector(introspectionUri, restTemplate))
							}
				}
	}

is there a better way to achieve it , i could not find the document or example.

**Comment by jzheaux** [comment]
Hi, @sandeepvedavyas, I think you are mixing two libraries together unintentionally. 

`OAuth2RestTemplate` and `ClientCredentialsResourceDetails` are from `spring-security-oauth`, which is a deprecated OAuth 2.0 extension library.

`NimbusOpaqueTokenIntrospector` is from Spring Security.

Please take a look at the Spring Security Reference docs for [propagating the access token](https://docs.spring.io/spring-security/site/docs/current/reference/html5/#bearer-token-propagation).

In the future, consider posting a question on [StackOverflow](https://stackoverflow.com/questions/ask) for better visibility. If you feel like you've found a bug, post a ticket to [Spring Security](https://github.com/spring-projects/spring-security).
